
// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Batch.Protocol
{
  using System;
  using System.Collections.Generic;
  using System.Linq;

  internal static partial class SdkInfo
  {
      public static IEnumerable<Tuple<string, string, string>> ApiInfo_BatchService
      {
          get
          {
              return new Tuple<string, string, string>[]
              {
                new Tuple<string, string, string>("BatchService", "Account", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "Application", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "Certificate", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "ComputeNode", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "File", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "Job", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "JobSchedule", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "Pool", "9999-09-09.99.99"),
                new Tuple<string, string, string>("BatchService", "Task", "9999-09-09.99.99"),
              }.AsEnumerable();
          }
      }
  }
}
